[server]
headless = true
enableCORS = false
enableXsrfProtection = false
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[global]
disableWidgetStateDuplicationWarning = true

[logger]
level = "error"

[client]
showErrorDetails = false
toolbarMode = "minimal"
showSidebarNavigation = false

[deprecation]
showfileUploaderEncoding = false
